# Generated by Django 2.1.5 on 2021-01-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hey',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
