# Generated by Django 2.1.5 on 2021-01-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_hey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hey',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
