# Generated by Django 2.1.5 on 2021-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210131_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hey',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
