# Generated by Django 2.1.5 on 2021-01-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210131_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hey',
        ),
    ]
